import React from 'react';
import { useStore } from '../store';


const AIRecommend: React.FC<any> = () => {
    const store = useStore();
   
  return (
     <div className=" bg-white rounded-xl shadow-lg p-8 m-6">
      {/* Header */}
      <div className="border-b border-gray-200 pb-6 mb-8">
        <div className="flex items-center gap-3 mb-2">
          <div className="w-10 h-10 bg-gradient-to-r from-blue-500 to-purple-600 rounded-full flex items-center justify-center">
            <span className="text-white font-bold text-lg">AI</span>
          </div>
          <h1 className="text-2xl font-bold text-gray-900">Business Profile Analysis</h1>
        </div>
        <p className="text-gray-600">AI-powered recommendations based on competitor benchmarking</p>
      </div>

      {/* Content */}
      <div className="prose max-w-none">
        {store.aiText && (
          <div className="bg-gray-50 p-6 rounded-lg shadow-sm">
            <h2 className="text-xl font-semibold mb-4">AI Recommendations</h2>
            <div className="text-gray-700 whitespace-pre-wrap">{store.aiText}</div>
            </div>)}
      </div>

      {/* Footer */}
      <div className="border-t border-gray-200 pt-6 mt-8">
        <div className="flex items-center justify-between text-sm text-gray-500">
          <span>Generated by AI Assistant</span>
          <span>{new Date().toLocaleDateString()}</span>
        </div>
      </div>
    </div>
  )
};

export default AIRecommend;